//
//  CharacterDetailsPresenter.swift
//  MarvelliciousVIP
//
//  Created by Mert Gürcan on 6.01.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterDetailsPresentationLogic {
    func presentCharacterDetail(response: CharacterDetails.ShowCharacterDetails.Response)
}

class CharacterDetailsPresenter: CharacterDetailsPresentationLogic {
    
    weak var viewController: CharacterDetailsDisplayLogic?
    
    func presentCharacterDetail(response: CharacterDetails.ShowCharacterDetails.Response) {
        var characterDetail = response.characterDetail
        characterDetail.resultDescription = ((characterDetail.resultDescription?.isEmpty) != nil) ? "No description" : characterDetail.resultDescription
        let viewModel = CharacterDetails.ShowCharacterDetails.ViewModel(characterDetail: characterDetail)
        viewController?.displayCharacterDetails(viewModel: viewModel)
    }
}
