//
//  CharacterDetailsInteractor.swift
//  MarvelliciousVIP
//
//  Created by Mert Gürcan on 6.01.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterDetailsBusinessLogic {
    func showDetails()
}

protocol CharacterDetailsDataStore {
    var characterDetail: Result? { get set }
}

class CharacterDetailsInteractor: CharacterDetailsBusinessLogic, CharacterDetailsDataStore {

    var characterDetail: Result?
    
    var presenter: CharacterDetailsPresentationLogic?
    var worker: CharacterDetailsWorker?
    
    func showDetails() {
        if let characterDetail = characterDetail {
            let response = CharacterDetails.ShowCharacterDetails.Response(characterDetail: characterDetail)
            presenter?.presentCharacterDetail(response: response)
        }
    }
}
