//
//  CharacterDetailsModels.swift
//  MarvelliciousVIP
//
//  Created by Mert Gürcan on 6.01.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CharacterDetails {
    // MARK: Use cases
    enum ShowCharacterDetails {
        struct Request {}
        
        struct Response{
            var characterDetail : Result
        }
        
        struct ViewModel {
            var characterDetail : Result
        }
    }
}
