//
//  CharacterListModels.swift
//  MarvelliciousVIP
//
//  Created by Mert Gürcan on 4.01.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CharacterList {
    // MARK: Use cases
    enum ShowCharacterList {
        struct Request {
            var page : Int
        }
        
        struct Response {
            var ListResponse : ListResponse
        }
         
        struct ViewModel {
            var results : [Result]
        }
    }
}
