//
//  CharacterListRouter.swift
//  MarvelliciousVIP
//
//  Created by Mert Gürcan on 4.01.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CharacterListRoutingLogic {
    func routeToCharacterDetail(indexPath: IndexPath)
}

protocol CharacterListDataPassing {
  var dataStore: CharacterListDataStore? { get }
}

class CharacterListRouter: NSObject, CharacterListRoutingLogic, CharacterListDataPassing {
    
    weak var viewController: CharacterListViewController?
    var dataStore: CharacterListDataStore?
    
    func routeToCharacterDetail(indexPath: IndexPath) {
        let vc = CharacterDetailsViewController()
        var destinationDS = vc.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS, indexPath: indexPath)
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    // MARK: Passing data
    func passDataToSomewhere(source: CharacterListDataStore, destination: inout CharacterDetailsDataStore, indexPath: IndexPath){
        let result = source.list?.data.results[indexPath.row]
        destination.characterDetail = result
    }
}
