//
//  CharacterListWorker.swift
//  MarvelliciousVIP
//
//  Created by Mert Gürcan on 4.01.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CharacterListWorker {
    
    var service : ServiceProtocol
    
    private var pageItem = 30
    
    init(service : Service) {
        self.service = service
    }
    
    private var loadResources : Resource<ListResponse>?
    
    func fetchCharacterList(from url : String, and page : Int, completion: @escaping(ListResponse) -> ()){
        
        let param : [String: Any] = ["limit" : "\(pageItem)", "offset" :"\((page-1) * pageItem)"]
        
        loadResources = Resource<ListResponse>(url: url, param: param)
        guard let loadResources = loadResources else {
            return
        }
        service.load(resource: loadResources) { result in
            switch result {
            case .succes(let data):
                if let data = data {
                    completion(data)
                }
            case .failure(let err):
                print("Failed")
            }
        }
    }
}
